### PR TITLE
Update peptides_proteins.rst

### PR DESCRIPTION
**Pull request by Ayesha-Feroz**
restructured the documentation and checked for spacing, etc.

### CODE REVIEW

**Comment by Ayesha-Feroz** [comment]
hmm build failed

**Comment by timosachsenberg** [comment]
You can see some hints in the action output: https://github.com/OpenMS/pyopenms-docs/actions/runs/8020779826/job/21911320614?pr=432
```
  Cell In[20], line 1
    Fixed: TESTMTEC(Carbamidomethyl)STMTESTR
                                    ^
SyntaxError: invalid syntax
```
probably something related to the brackets

**Comment by timosachsenberg** [comment]
please ping me again for a review once the issues are resolved and I will review

**Comment by timosachsenberg** [comment]
any update here?

**Comment by sasadshah11** [comment]
https://github.com/OpenMS/pyopenms-docs/pull/433

**Pull request closed without merging**
