### PR TITLE
Update py version of wheel to install.

### PR DESCRIPTION
**Pull request by jpfeuffer**
Probably ubuntu_latest is now 22.04 and comes with py 3.10

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Otherwise we should parse the python version and pass it to the glob pattern for the wheel

**Review by timosachsenberg — APPROVED** [review]

**Comment by jpfeuffer** [comment]
Was also tagging for some input on the way forward

**Comment by timosachsenberg** [comment]
"Otherwise we should parse the python version and pass it to the glob pattern for the wheel"
yeah I think that works but might also a be a bit fragile

Wouldn't we like to set the python version dependent on the (e.g., highest python version) wheel that is available? e.g., choose the compatible python version

Not sure if this can be injected into:
```
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
```

**Comment by jpfeuffer** [comment]
But there is not other way, you cannot let python find the correct wheel to install for you. You have to tell it.
Unless you have a pypi repo

**Pull request merged**
