### PR TITLE
DONT MERGE Master+ipynb

### PR DESCRIPTION
**Pull request by poshul**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Wait, the push should be done automatically for each push on master, right? Or what is this PR for?
Not that it's the best solution, but be careful if you change master+ipynb

**Comment by poshul** [comment]
We don't push the ipynb's back to Master. This was just a lazy way to test the GHA activation. I tried to move forward with https://github.com/OpenMS/pyopenms-docs/pull/320 but using conda in the action spins forever: https://github.com/OpenMS/pyopenms-docs/actions/runs/6719647447/job/18261670898?pr=320

**Comment by jpfeuffer** [comment]
I think we should use (micro)mamba instead of conda these days. Might help with runtime.

**Comment by timosachsenberg** [comment]
ah ok came to say same thing... we don't usually push back the notebooks into master (to keep it clean).

**Comment by poshul** [comment]
Something I did realize is that the way we do it now means past version of
the notebooks get wiped every time master+ipynb gets updated.

**Comment by jpfeuffer** [comment]
Yep. That's mainly why this branch should never be touched manually 😅

**Pull request closed without merging**
