### PR TITLE
Update apidoc.rst

### PR DESCRIPTION
**Pull request by poshul**
testing for linting

### CODE REVIEW

**Comment by jpfeuffer** [comment]
@poshul It does not work.

**Comment by poshul** [comment]
> 
It's been a bit since I did anything with the docs side. How can I tell? The github actions log doesn't list specific files.

**Comment by jpfeuffer** [comment]
That's exactly what's wrong. But you are an expert in tj-changed-files. It just does not pick up when things get changed!

**Comment by jpfeuffer** [comment]
It is correct if it picks up apidocs.rst but not template.rst

**Comment by poshul** [comment]
> 

ah. So it wasn't picking up anything before. I'll mess with it to see if I can get some better results.

**Comment by poshul** [comment]
hmm. Looking at a run from before I changed anything I still see empty file lists: https://github.com/OpenMS/pyopenms-docs/actions/runs/3695159848/jobs/6257203130

**Comment by jpfeuffer** [comment]
But that PR does not have any changed rst files. So it behaves correct in this case.

**Pull request closed without merging**
