### PR TITLE
Update OpenMS.svg

### PR DESCRIPTION
**Pull request by poshul**
Use new OpenMS logo

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Wait. Didn't we create a pyopenms through a large effort with voting procedure etc?
Was this discarded again?

**Comment by poshul** [comment]
Funny you should ask. That's what I was looking for when I found this was still using the old OpenMS logo. We have the png here: https://openms.de/images/pyopenms-logo.png but I can't easily find the svg version

**Comment by jpfeuffer** [comment]
@timosachsenberg you created it in the end, right?
Do you have an SVG?

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/images

**Comment by timosachsenberg** [comment]
can we add a bit margin? looks a bit cramped on my pc (looks better on the screenshot...) image

**Comment by jpfeuffer** [comment]
Sure. The css is here: https://github.com/OpenMS/pyopenms-docs/blob/master/docs%2Fsource%2F_static%2Fcustom.css#L123

**Pull request merged**
