### PR TITLE
Mentioning that "plot_spectrum" function has been named differently

### PR DESCRIPTION
**Pull request by JeeH-K**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Ideally, this should be in the Changelog instead.

**Comment by timosachsenberg** [comment]
Do we have a proper pyOpenMS changelog? Or worries we need to add something to the readthedocs page? Btw I have seen these kind of “API has changed” or “compatibility notes” before in other projects and found them helpful. What is your main concern here? Clutter?

**Comment by jpfeuffer** [comment]
Yes clutter. If we do this for every change, it will become completely unreadable. It will be unreadable already, if we actually added all changes to the API since 2.X right now.

**Comment by jpfeuffer** [comment]
And where to add it? Everytime plotting is mentioned in the docs? This is just not scalable.
The maximum I would agree with is in the module API documentation.

**Comment by jpfeuffer** [comment]
You can also write a migration guide or something like that. But IMHO this is basically an extended changelog then.

**Comment by timosachsenberg** [comment]
OK, I agree that this can escalate quickly :)
I would be fine with either put this note in:
https://pyopenms.readthedocs.io/en/latest/_autosummary/pyopenms.plotting.html#module-pyopenms.plotting
or provide a good answer in the issue so people can also look it up through the issue tracker...

**Comment by jpfeuffer** [comment]
Problem is, the user asked on discussions and issues. I answered on discussions and refused to answer twice.

**Comment by jpfeuffer** [comment]
I edited the last reply now and it should be clear from the issue.

**Comment by timosachsenberg** [comment]
🙏

**Pull request closed without merging**
