### PR TITLE
Tutorial enhancements

### PR DESCRIPTION
**Pull request by cbielow**
This PR enhances the pyOpenMS docs

- enhance glossary and links 
- fix broken links 
- update installation and build instructions for sphinx 
- remove unused (and duplicated) page on hyperscore 
- update domain specific terms in glossary

### CODE REVIEW

**Comment by matteopilz** [comment]
Any idea why the notebook test is failing? Is it because of the additional packages?

**Comment by cbielow** [comment]
and the "new" packages are not actually 'extra'. They are part of some docs, which the respective developers seem to have used locally, but did not add to the `requirements.txt`. The packages were optional, so they just cause warnings when running sphinx-build, not errors.

**Comment by jpfeuffer** [comment]
It's either a corrupt package or an incomplete download. I would restart the build.

Where do we use ipython syntax?

**Comment by cbielow** [comment]
> It's either a corrupt package or an incomplete download. I would restart the build.

IIRC there was a rebuild after my last commit and the error did not chance.
I've remove the `hyperscore` rst which was unreferenced according to sphinx (and git grep). Yet the build fails with 
`[NbConvertApp] WARNING | pattern 'docs/source/hyperscore.ipynb' matched no files`, so it might be related to that.

> Where do we use ipython syntax?

here: [docs/source/user_guide/interfacing_ml_libraries.rst:.. code-block:: ipython3](https://github.com/OpenMS/pyopenms-docs/blob/master/docs/source/user_guide/interfacing_ml_libraries.rst?plain=1#L17)

**Comment by jpfeuffer** [comment]
Yep. I think the action is wrong. It tries to check all changed files. Deleted files are changed files as well but of course cannot be tested anymore.

I think the previous error with the download was a hiccup.

**Comment by jpfeuffer** [comment]
Ah hmm that is quite some overhead to install ipython just for colorizing two lines..
But if there is no alternative..

**Comment by cbielow** [comment]
ok, this seems to have done it. The list of changed files now excludes deleted files.

**Review by matteopilz — APPROVED** [review]

**Pull request merged**
