### PR TITLE
[Update] Readthedocs build

### PR DESCRIPTION
**Pull request by jpfeuffer**
Fixes adding of buttons to the header.
See https://pyopenms.readthedocs.io/en/update-rtdbuild/

### CODE REVIEW

**Comment by timosachsenberg** [comment]
awesome

**Comment by timosachsenberg** [comment]
there is still the second binder button but I guess that is an artefact

**Comment by jpfeuffer** [comment]
The big one on the bottom? No, this has to be removed. Superfluous now.

**Comment by jpfeuffer** [comment]
Hmmm not sure. I think we should rather mention it in the introduction and/or in a new chapter or find some place more prominent?

**Pull request merged**
