### PR TITLE
Update spectrum_normalization.rst

### PR DESCRIPTION
**Pull request by Ayesha-Feroz**
This commit enhances the 'Spectrum Normalization' section of the documentation. The changes include the inclusion of images of before normalization, after normalization, and TIC normalization. I also tried to add some extra explanation, and images are stored in the img folder and given a relative path in code.

### CODE REVIEW

**Comment by timosachsenberg** [comment]
I don’t see the images.

**Comment by Ayesha-Feroz** [comment]
> I don’t see the images.

hmm let me see btw i have uploaded it here      https://github.com/OpenMS/pyopenms-docs/commit/cae748a47938f4cf87967fc001874b78bb7f1b77

**Comment by timosachsenberg** [comment]
Please don’t just upload stuff to master. Correct way would be to add it them to this pull request so everything that belongs together stays together.

**Comment by Ayesha-Feroz** [comment]
> Please don’t just upload stuff to master. Correct way would be to add it them to this pull request so everything that belongs together stays together.

ok Timo got it.

**Pull request merged**
