### PR TITLE
test blacken

### PR DESCRIPTION
**Pull request by jpfeuffer**

### CODE REVIEW

**Comment by matteopilz** [comment]
I left some comments on the closed pr, it looks like it doesn't work.

**Comment by jpfeuffer** [comment]
It does work but always reports exit code 1.
I think I am going to write my own script. Blacken is too bugged. See all my issues:
https://github.com/adamchainz/blacken-docs/issues/

**Comment by matteopilz** [comment]
Before you do that, I would like to try it with flakeheaven again if possible. It seems the output is compatible with reviewdog.

**Comment by matteopilz** [comment]
I think we could tell flakeheaven to ignore a specific line e.g. `:linenos:` with `:linenos: # noqa`.

**Comment by jpfeuffer** [comment]
@matteopilz  works now.

**Pull request closed without merging**
