### PR TITLE
Add furo theme

### PR DESCRIPTION
**Pull request by greengypsy**
Fixes https://github.com/OpenMS/pyopenms-docs/issues/284.

I've added furo by setting the theme in the conf.py file and adding the package to requirements.txt.

You can see the generated output at [this link](https://greengypsy-pyopenms.readthedocs.io/en/add-furo-theme/).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Did you see our discussion about the "Run on Binder" button? Do you have any good suggestions?
Should we try sphinx-book-theme for both documentations? It is very similar with additional support for a header on mobiles.

**Comment by greengypsy** [comment]
This is well beyond my knowledge in web design. I am struggling to come up with a solution so I've asked Rahul to have a look.

**Comment by jpfeuffer** [comment]
Unfortunately the feature request is declined in furo.
https://github.com/pradyunsg/furo/issues/57

**Comment by jpfeuffer** [comment]
Currently the code is in the breadcrumbs:
https://github.com/OpenMS/pyopenms-docs/blob/master/docs/source/_templates/breadcrumbs.html

I made the breadcrumbs header sticky on desktop.

**Pull request closed without merging**
